name: Jest Tests

on:
  push:
    branches:
      - main  
      - deployment

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install
      
    - name: Change permissions
      run: chmod +x node_modules/.bin/jest
      
    - name: Run Jest tests
      run: npm test